/**
 * Cookies that carry the NPS invitation off the URL (issue #1666).
 *
 * The invite link is `/nps?token=…`, and the token is both a bearer
 * credential and reversible PII (`base64url(JSON)` with e-mail and first
 * name — see lib/nps-invite.ts). Zaraz's automatic Pageview fires before any
 * page code runs and ships the full URL (query included) to GA4 as
 * `page_location`, so a client-side `history.replaceState` is too late.
 *
 * Instead the edge (`lib/nps-invite-redirect.ts`) swaps the query for a pair
 * of cookies and redirects to `/nps/?i=<tab ref>` — the HTML that loads
 * analytics never sees the secret. The tab ref is a fresh random value per
 * redirect, generated by the edge: it names the cookie pair, so each tab
 * finds its own invite even when several invites are opened in the same
 * browser (a shared, fixed cookie name let the last redirect overwrite the
 * invite of a tab that hadn't loaded yet, and that tab's answers landed on the
 * other customer's record). It is not a credential and is tied to nothing
 * outside this browser, so it identifies no one in analytics.
 *  - `nps_invite_<ref>`: the token. `HttpOnly` (page JS and tag scripts can't
 *    read it), `SameSite=Strict` (a cross-site page can't submit on the
 *    customer's behalf), `Path=/api/submit-nps` (sent nowhere else).
 *  - `nps_invite_info_<ref>`: readable by the page, `Path=/nps`, same
 *    lifetime. JSON with the first name from the verified payload (the
 *    greeting). Its presence is how the page tells "has an invite" from
 *    "invalid link".
 *
 * Shared by the edge redirect, the submit handler and the page, so it must
 * stay free of server-only imports.
 */

const TOKEN_COOKIE_PREFIX = 'nps_invite_';
const INFO_COOKIE_PREFIX = 'nps_invite_info_';
export const NPS_INVITE_TOKEN_COOKIE_PATH = '/api/submit-nps';
export const NPS_INVITE_INFO_COOKIE_PATH = '/nps';

/** Query param of the clean `/nps/` URL that carries the tab ref. */
export const NPS_INVITE_REF_PARAM = 'i';

const INVITE_REF_PATTERN = /^[a-f0-9]{32}$/;

/**
 * Long enough to fill the form after opening the e-mail, short enough that a
 * shared computer doesn't keep a live credential around for days. Reopening
 * the e-mail link re-issues the cookies while the invite itself is valid.
 */
export const NPS_INVITE_COOKIE_MAX_AGE_SECONDS = 2 * 60 * 60;

export function createNpsInviteRef(): string {
    return crypto.randomUUID().replace(/-/g, '');
}

export function isNpsInviteRef(value: unknown): value is string {
    return typeof value === 'string' && INVITE_REF_PATTERN.test(value);
}

export function npsInviteTokenCookieName(ref: string): string {
    return `${TOKEN_COOKIE_PREFIX}${ref}`;
}

export function npsInviteInfoCookieName(ref: string): string {
    return `${INFO_COOKIE_PREFIX}${ref}`;
}

interface CookieOptions {
    path: string;
    maxAgeSeconds: number;
    httpOnly: boolean;
    /** False only on plain-HTTP local dev, where browsers drop `Secure` cookies off localhost. */
    secure: boolean;
}

function serializeCookie(name: string, value: string, options: CookieOptions): string {
    const parts = [
        `${name}=${encodeURIComponent(value)}`,
        `Path=${options.path}`,
        `Max-Age=${Math.max(0, Math.floor(options.maxAgeSeconds))}`,
        'SameSite=Strict',
    ];
    if (options.httpOnly) parts.push('HttpOnly');
    if (options.secure) parts.push('Secure');
    return parts.join('; ');
}

export interface NpsInviteInfo {
    name: string;
}

export function buildNpsInviteCookies(
    params: { ref: string; token: string; info: NpsInviteInfo; maxAgeSeconds: number },
    secure: boolean,
): string[] {
    return [
        serializeCookie(npsInviteTokenCookieName(params.ref), params.token, {
            path: NPS_INVITE_TOKEN_COOKIE_PATH,
            maxAgeSeconds: params.maxAgeSeconds,
            httpOnly: true,
            secure,
        }),
        serializeCookie(npsInviteInfoCookieName(params.ref), JSON.stringify(params.info), {
            path: NPS_INVITE_INFO_COOKIE_PATH,
            maxAgeSeconds: params.maxAgeSeconds,
            httpOnly: false,
            secure,
        }),
    ];
}

export function buildClearedNpsInviteCookies(ref: string, secure: boolean): string[] {
    return buildNpsInviteCookies({ ref, token: '', info: { name: '' }, maxAgeSeconds: 0 }, secure);
}

/** Reads one cookie from a `Cookie` header or `document.cookie` string. */
export function readCookie(cookieHeader: string | null | undefined, name: string): string | null {
    if (!cookieHeader) return null;
    for (const pair of cookieHeader.split(';')) {
        const separator = pair.indexOf('=');
        if (separator === -1) continue;
        if (pair.slice(0, separator).trim() !== name) continue;
        try {
            return decodeURIComponent(pair.slice(separator + 1).trim());
        } catch {
            return null;
        }
    }
    return null;
}

/** Parses `nps_invite_info_<ref>`; `null` when absent or not the shape the edge writes. */
export function parseNpsInviteInfo(value: string | null): NpsInviteInfo | null {
    if (value === null) return null;
    try {
        const parsed: unknown = JSON.parse(value);
        if (!parsed || typeof parsed !== 'object') return null;
        const { name } = parsed as Record<string, unknown>;
        if (typeof name !== 'string') return null;
        return { name };
    } catch {
        return null;
    }
}
