export function normalizeText(value: string): string {
    return value
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .toLowerCase()
        .replace(/\s+/g, ' ')
        .trim();
}

export function normalizeLabel(value: string): string {
    return normalizeText(value).replace(/[–—]/g, '-');
}

export function escapeRegExp(value: string): string {
    return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

export function hasAliasMatch(text: string, alias: string): boolean {
    const normalizedAlias = normalizeText(alias);
    if (!normalizedAlias) return false;

    // Match aliases as independent terms to avoid false positives like "ira" inside "emirados"
    const pattern = new RegExp(`(?:^|[^a-z0-9])${escapeRegExp(normalizedAlias)}(?:$|[^a-z0-9])`, 'i');
    return pattern.test(text);
}

export function resolveMaxMessageLength(rawValue: string | undefined): number {
    const parsed = Number.parseInt(rawValue || '4000', 10);
    return Number.isFinite(parsed) && parsed > 0 ? parsed : 4000;
}

export const MAX_CONTENTS_TOTAL_LENGTH = 200_000;

export function hasOversizedPayload(contents: unknown[]): boolean {
    return JSON.stringify(contents).length > MAX_CONTENTS_TOTAL_LENGTH;
}

export function hasOversizedMessage(contents: unknown, maxMessageLength: number): boolean {
    if (!Array.isArray(contents)) return false;

    return contents.some((msg: unknown) => {
        if (typeof msg !== 'object' || !msg) return false;
        const parts = (msg as { parts?: unknown[] }).parts;
        if (!Array.isArray(parts)) return false;

        return parts.some((part: unknown) => {
            if (typeof part !== 'object' || !part) return false;
            const text = (part as { text?: unknown }).text;
            return typeof text === 'string' && text.length > maxMessageLength;
        });
    });
}

function extractRecord(value: unknown): Record<string, unknown> | undefined {
    if (!value || typeof value !== 'object' || Array.isArray(value)) return undefined;
    return value as Record<string, unknown>;
}

export function extractBudgetToolCallFromText(
    text?: string,
): { name: 'generate_budget_link'; args: Record<string, unknown> } | undefined {
    if (!text || !text.includes('generate_budget_link')) return undefined;

    const candidates: string[] = [text.trim()];

    const fencedMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
    if (fencedMatch?.[1]) {
        candidates.push(fencedMatch[1].trim());
    }

    if (text.includes('"tool_call"')) {
        const start = text.indexOf('{');
        const end = text.lastIndexOf('}');
        if (start >= 0 && end > start) {
            candidates.push(text.slice(start, end + 1).trim());
        }
    }

    for (const candidate of candidates) {
        try {
            const parsed = JSON.parse(candidate);
            const record = extractRecord(parsed);
            if (!record) continue;

            const toolCall = typeof record.tool_call === 'string'
                ? record.tool_call
                : typeof record.name === 'string'
                    ? record.name
                    : undefined;
            if (toolCall !== 'generate_budget_link') continue;

            const args = extractRecord(record.arguments ?? record.args);
            if (!args) continue;

            return { name: 'generate_budget_link', args };
        } catch {
            // Ignore invalid candidates and keep scanning
        }
    }

    return undefined;
}

export function stripToolCallJsonBlock(text: string): string {
    return text
        .replace(/\{[\s\S]*"tool_call"\s*:\s*"generate_budget_link"[\s\S]*\}\s*$/m, '')
        .replace(/```(?:json)?[\s\S]*?```/gi, '')
        .trim();
}

// Extract chips JSON block from text (e.g., {"chips": ["option1", "option2"]})
export interface ExtractChipsResult {
    text: string;
    chips?: string[];
}

export function extractChipsFromText(text: string): ExtractChipsResult {
    if (!text) return { text };

    // Match JSON with chips field, raw markdown arrays like "**chips:** [...]", "chips: [...]", or a trailing JSON array.
    const chipsMatch = text.match(/\{\s*"chips"\s*:\s*(\[[^\]]*\])\s*\}/i) ||
        text.match(/\*?\*?chips\*?\*?:?\*?\*?\s*(\[[^\]]*\])/i) ||
        text.match(/(?:\n|^)\s*(\[[^\]]*\])\s*$/); // Fallback: just an array at the end of the string

    if (!chipsMatch) return { text };

    try {
        // Handle smart quotes and single quotes often generated by Gemini's markdown
        const rawJsonString = chipsMatch[1].replace(/['“”]/g, '"').replace(/\s+/g, ' ');
        const parsedArray = JSON.parse(rawJsonString);

        if (Array.isArray(parsedArray)) {
            // Map objects (e.g. {"label": "x", "value": "x"}) to simple strings if Gemini hallucinates
            const chipsArray = parsedArray.map(item => {
                if (typeof item === 'string') return item;
                if (typeof item === 'object' && item !== null) {
                    return item.label || item.value || item.text || String(item);
                }
                return String(item);
            }).filter(Boolean);

            if (chipsArray.length > 0) {
                // Remove the matched block and any residual newlines
                const cleanedText = text.replace(chipsMatch[0], '').trim();
                return { text: cleanedText, chips: chipsArray };
            }
        }
    } catch (error) {
        // Invalid JSON, log for debugging and return original text
        console.warn('Failed to parse chips from AI response', { error });
    }

    return { text };
}
