name: CI
permissions:
  contents: read
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build / Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9

      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Node version check
        run: node -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run test:regression

      - name: Typecheck
        run: pnpm run typecheck

      - name: Install Puppeteer Browser
        run: npx puppeteer browsers install chrome

      - name: Build
        run: pnpm run build

      - name: Check bundle size
        run: pnpm run test:size

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist
